### ISSUE TITLE
Can't seem to get it working

### ISSUE THREAD

**Issue by trosh** [soheilpro/zsh-vi-search#1]
Hello, hope this is just me being stupid.

My `.zshrc` looks like this:

    ...
    bindkey -v
    ...
    . $HOME/src/zsh-vi-search/src/zsh-vi-search.zsh
    ...

When I load a new shell, I do

    $ echo hello
    $ <esc>?cho

And I'm left in command mode at the current empty command.
At best if I use `<esc>/` I have basic vi-mode history search behaviour.

Am I doing something wrong ?

I'm putting this as an issue only because I assume I'm doing something wrong
and I figured the readme could be slightly more helpful.

Thanks

**Comment by soheilpro** [comment]
This tool lets you use search to edit the current line, instead of using arrow keys or other vim movement commands.

For example, suppose you have typed this command:
```
$ curl http://google.com<CURSOR>
```

and now you want to change "http" to "https".

To do this, press `ESC` to go into normal mode, then press `/` to activate search. Now type `:` and press enter. This will put the cursor just before `:`:

```
$ curl http<CURSOR>://google.com
```

Now, you can simply go back into the insert mode and type `s`.

**Comment by trosh** [comment]
Oh yeah OK I get it, I just immediatly assumed it could also jump through history *as well*

That would make it complete in my opinion but it's already quite good :+1:

**Comment by soheilpro** [comment]
Thanks. I'm glad you've found this useful :)
